# This rule is not used by the project k8s-ghost itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to blog.kubesource.toolbox resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-ghost
    app.kubernetes.io/managed-by: kustomize
  name: ghost-viewer-role
rules:
- apiGroups:
  - blog.kubesource.toolbox
  resources:
  - ghosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - blog.kubesource.toolbox
  resources:
  - ghosts/status
  verbs:
  - get
